### ISSUE TITLE
HomeBridge stops working after a time

### ISSUE THREAD

**Issue by nfarina** [nfarina/homebridge#11]
I'm posting this as a discussion topic for an issue I've been having personally to see if it's been a problem for anyone else.

I have my personal homebridge running on an old Mac Mini with about a dozen or so accessories loaded. Everything works very well generally, but after the server has been running for a day or so, I'm unable to get Siri to do anything until I restart the server.

I've worked around this by making the server auto-restart daily, but before proposing that this be "the solution", I wanted to know if anyone else has experienced this.

/cc @jnewland, @maddox

**Comment by maddox** [comment]
I've been running for about 5 days and haven't seen total complete failure. I have seen Siri fail and tell me it couldn't do something though. After trying again it's worked though.

I'm currently just running the server inside a screen instance. I haven't done anything to add it to `launchd` yet. (If I do, I'll open a pull.)

**Comment by nfarina** [comment]
Well that's good to hear. Perhaps my network has some issues.

**Comment by suhajdab** [comment]
I have the same problem. I can connect to my rpi, I can see output from the script about New Sessions and alike, but when I talk to Siri, it doesn't work. It's a different state compared to when Homebridge is completely off. Siri says it couldn't get a response and unlike normally there is nothing in the output reflecting on the request.

**Comment by nfarina** [comment]
@suhajdab Does it ever work? Or does it work at first then stop working after a time (how long)?

**Comment by nfarina** [comment]
I think I'm going to blame `discoveryd` for this :) Closing for now; will see how things go under `mDNSResponder`.

**Comment by jnewland** [comment]
@nfarina that's my hunch as well. What a disaster.

**Comment by suhajdab** [comment]
@nfarina Sorry for the late response. So it always starts off working, but after a while (no idea how long, but not a few minutes) it stops and Siri says "Hmmm..." after a period of waiting.

**Comment by nfarina** [comment]
@suhajdab And after that it ceases to work? If so and since you're on a rpi, I'm not sure if discoveryd is to blame after all. Could you try the `forever-restart` branch and see if that "fixes" your problem?

**Comment by nfarina** [comment]
Update: I upgraded my Mac Mini running homebridge to El Capitan which replaces `discoveryd` with `mDNSresponder` and lo and behold, the problem is gone. The server has been happily running for days.

**Comment by maddox** [comment]
lol (2)

**Comment by jnewland** [comment]
:star: (2)

**Comment by desvdp** [comment]
Hi, any comments related to the RPi? 
At least my setup, running on a RPi2, still becomes unresponsive after a day or so.  I'm not sure it's related but it does mention some warnings related to the Avahi daemon running in compatibility mode.

Unless Apple pulls an amazing trick tonight running El Capitan on RPi is not an option ;-) ...

**Comment by nfarina** [comment]
My RPi2 has been running latest Homebridge for weeks without any issues. I suppose it could be a problem related to open sockets - can you paste the result of running `netstat -a -n -p tcp | grep 51827`?

**Comment by desvdp** [comment]
@nfarina Hi Nick, I did some checking on the socket myself, as far I understand I don't see anything unusual :

> me@raspberrypi ~ $ sudo netstat -a -n -p tcp | grep 51826
> tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN      28356/node
> tcp        0      0 192.168.1.194:51826     192.168.1.103:49534     ESTABLISHED 28356/node

or by PID: 
> me@raspberrypi ~ $ sudo netstat -a -n -p tcp | grep 28356
> tcp        0      0 0.0.0.0:54826           0.0.0.0:*               LISTEN      28356/node
> tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN      28356/node
> tcp        0      0 127.0.0.1:54826         127.0.0.1:60990         ESTABLISHED 28356/node
> tcp        0      0 192.168.1.194:51826     192.168.1.103:49534     ESTABLISHED 28356/node
> tcp        0      0 127.0.0.1:60990         127.0.0.1:54826         ESTABLISHED 28356/node 

related to the posts above: 
I do get the infamous avahi warnings ... 
> *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility
> *** WARNING *** Please fix your application to use the native API of Avahi!

Do you believe this can have anything to do with it? 
Some possibly related info:
> me@raspberrypi ~/homebridge $ node -v
> v0.12.6
> me@raspberrypi ~/homebridge $ uname -a
> Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
> me@raspberrypi ~/homebridge $ cat /etc/issue.net
> Raspbian GNU/Linux 7
> me@raspberrypi ~/homebridge $ dpkg -s libavahi-compat-libdnssd-dev
> Package: libavahi-compat-libdnssd-dev
> Status: install ok installed
> Priority: optional
> Section: libdevel
> Installed-Size: 186
> Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
> Architecture: armhf
> Source: avahi
> Version: 0.6.31-2
> Depends: libavahi-compat-libdnssd1 (= 0.6.31-2), libavahi-client-dev

**Comment by KhaosT** [comment]
@desvdp those all looks good... next time when this happens, can you try to use your computer to access your Raspberry Pi with url http://IPofRaspberryPi:51826/accessories and see if you can get a response. If you received response then that might be a different issue on iOS side.

**Comment by desvdp** [comment]
@KhaosT Thanks for the suggestion, I'll test the link once it goes down again (just restarted it for the test above). Btw: regarding iOS, just before your response can in I was edited the post above to mention I'm on iOS 8.4.1 not sure how big the impact of not being on 9 is ...

**Comment by cflurin** [comment]
@desvsp: I'm running homebridge on a mac-mini and simultaneously on a RPi B without any issues.
Both are connected with my iPhone iOS 8.4.1.
Are you running the latest Raspbian version (4.1.6+) ?
I' didn't use my RPi for a long time so I had to do:
```sudo apt-get dist-upgrade```

**Comment by desvdp** [comment]
Update:
this morning I upgraded the dist as suggested in the previous post. I rebooted the system and restarted the homebridge. 
after ±9 hours the system became unresponsive again. 
@KhaosT : The accessories URL is still responsive. 
@nfarina nfarina: I queried the open sockets again while the iPhone is unable to connect:
> me@raspberrypi ~ $ sudo netstat -a -n -p tcp | grep 2367
> tcp        0      0 0.0.0.0:54826           0.0.0.0:*               LISTEN      2367/node
> tcp        0      0 0.0.0.0:54827           0.0.0.0:*               LISTEN      2367/node
> tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN      2367/node
> tcp        0      0 127.0.0.1:43949         127.0.0.1:54827         ESTABLISHED 2367/node
> tcp        0      0 192.168.1.194:51826     192.168.1.103:50398     ESTABLISHED 2367/node
> tcp        0      0 127.0.0.1:44730         127.0.0.1:54826         ESTABLISHED 2367/node
> tcp        0      0 127.0.0.1:54827         127.0.0.1:43949         ESTABLISHED 2367/node
> tcp        0      0 127.0.0.1:54826         127.0.0.1:44730         ESTABLISHED 2367/node
> tcp        0      0 192.168.1.194:51826     192.168.1.229:49888     ESTABLISHED 2367/node
> unix  3      [ ]         STREAM     CONNECTED     9403     2367/node
> unix  3      [ ]         STREAM     CONNECTED     9400     2367/node
> unix  3      [ ]         STREAM     CONNECTED     9401     2367/node 

FYI: 192.168.1.229 is my desktop (where I'm testing the accessories URL), 192.168.1.103 is my IPhone, 194 the RPi.
This afternoon I synced up my iPad via iCloud: this worked fine, both the iPhone and iPad were able to control the lights. 

What I'm currently observing: on the iPhone (which is the device I used to configure the apps) the Insteon+ app has all the devices greyed out, the Eve app reports all devices as "unreachable". I then checked the iPad (which only has the Insteon+ app), the same state is observed: just like the iPhone, all icons are also greyed out.  

__A question:__ could this state result when a get/set callback is not called timely?  If this would be the case: is a variable/observable item I can check to confirm the diagnose? 

(btw: the RPi is connected to LAN via an Ethernet cable)

**Comment by cflurin** [comment]
I had similar issues with my mac mini connected via Ethernet. I'd try connecting your RPi with a WiFi-Dongle.

**Comment by desvdp** [comment]
@cflurin  I currently don't have a dongle lying around, but I'm happy to pick one up and give it a try. But just out of curiosity, I don't see how this would make a difference: is there a technical reason why Wifi would yield better results, I always assumed cabled had all the advantages (well except some auth features specific to Wifi but I assume these are not relevant here... ).
to make sure: should I look for a dongle with specific features (or a specific type?) 

@nfarina you mentioned you're running the RPi2 for weeks, what connection type are you using, is this also using a Wifi dongle?

**Comment by nfarina** [comment]
Mine is connected via built-in Ethernet. And yes, it's possible that iOS will "give up" on an otherwise-working server for some reasons like, get/set not responded to, /accessories JSON invalid, etc

**Comment by desvdp** [comment]
@nfarina Is there a way to confirm this is what is happening? Preferably from the RPi end as I don't have an Apple Dev account.

**Comment by desvdp** [comment]
let me ask a better question first: the platform I'm building interfaces to a 10yr old home automation system over rs232 (yeah ... I know ... ), as a result it can take ~700ms for a status update to come in... if multiple updates are requested they get queued. If the client request more than 1 state worst case it takes  x * 700ms for the RPi to respond.   
So question #1, are you aware of any response times that must be met? and #2: is there a way (i.e by returning an error (?) to hold off the client without hanging up entirely? 
Honestly I don't believe this is the root cause of the issue as I've seen cases where it didn't respond to the first command after being idle for a while... I just want to be sure I don't have to investigate this path...

**Comment by cflurin** [comment]
Okey, apparently it must be an issue with my LAN/WLAN layout.
@desvdp : how did you connect the automation system (rs232 hardware, baudrate)?

**Comment by volschin** [comment]
@desvdp : Could you use the rs232 to actively inform homebridge of occuring changes? The FHEM Plattform shim has implemented some chaching regarding the values, to be a lot more responsive.

**Comment by nzhome** [comment]
@devsvdp both my raspberry PI and PI2 can run for weeks and weeks, and I have multiple devices coming and going, my pi server gets a hammering during testing, I only shut the server down for updates basically. I really can not break it..  so I would put a lot of focus on sockets and what your router is and isn't passing through.    mdns is a network protocol and is subjected to a lot of NAT and other rules inside your wifi router.   first reset your router, see if that helps..  second try a wifi dongle, because that will force your wifi router to process packets using the wifi engine in your router rather than the ethernet engine. yep they are different.  being a network engineer by trade I have seen 1000s of different issues, so I can't pin point this one yet. Need more info, more testing, and more debugging to get to the bottom this one...

**Comment by nzhome** [comment]
@devsdp  I found the perfect article for you, to help your understanding...

http://superuser.com/questions/730288/why-do-some-wifi-routers-block-multicast-packets-going-from-wired-to-wireless

**Comment by nzhome** [comment]
@devsdp  and the list goes on...

http://www.networkworld.com/article/2161302/lan-wan/apple-seeks-standard-to-appease-angry-university-net-managers.html

**Comment by desvdp** [comment]
@nzhome The multicast actually makes sense. I agree packets have to be routed between cabled and wifi, where most probably some filtering will be applied. The irony is I have an Apple router (Airport Express), you'd expect that to work, right ;-) . Also, I'm using the router an access point in "Bridge mode", I had hoped less filtering would be going on here. 
I'm currently searching Google for mDNS query tools (I found some running on iOS, but would prefer a more elaborate on the console of my desktop).

**Comment by nzhome** [comment]
@devsdp  unfortunately Apple Airport Express is also susceptible, and it is not apples core product, and it shows a little :)

**Comment by nzhome** [comment]
if you have a spare router to plugin for a week, you will know for sure.  I have 4 routers in my house for that purpose, 2 are now retired to the back of the cupboard they were that bad, and were top of the line brands.

**Comment by desvdp** [comment]
I'll see if I can find one ... It won't be a recent one ;-) , probably I might have an old linksys lying around. That's not the one on your cupboard is it?

**Comment by cflurin** [comment]
Coming back on my post above: If the router doesn't solve the problem the next easiest step is to try with a WiFI dongle. I'm using the TL-WN725N v2 but I'll try with the official WiFi dongle > http://www.adafruit.com/products/2638.

and again it may also  be your RS232 hardware, that causes this issue.

**Comment by desvdp** [comment]
@cflurin  Actually ... I'm starting to wonder if my netgear prosafe switch doesn't have anything to do with it... currently reading manuals (and trying to find a windows box to configure it :-( )

**Comment by cflurin** [comment]
hmm, try connecting the RPi directly to your router.

**Comment by desvdp** [comment]
@cflurin don't believe that would do any good, my setup is router<-> switch <-> AP 
The router only has one connection being the switch, the wireless access point (and everything else in the house) is on the switch.... so connecting the RPi to the router will move it away further ...

**Comment by volschin** [comment]
Netgear Prosafe should be fine depending on the model, I use GS116ev2 and GS108ev3, both support multicast, but need to be configured for this.

**Comment by cflurin** [comment]
@desvdp: I see (Almost all new router has 4 or more ports). It seems to me that you are using old devices. My suggestion: buy new router/wifi-dongle, this would save you a lot of troubles.

**Comment by desvdp** [comment]
@volschin When you say "need to be configured for this": can you specify how you configured it? currently I disableb IGMP snooping, and unchecked/disabled the "validate header" and "block unknown multicast address" ... is that the correct way, or did you involve VLANs ? Are there any other setting that might affect it ?

**Comment by volschin** [comment]
I have activated IGMP snooping without a special VLAN and deactivated validation of IGMPv3 headers and unknown multicast address blocking.
I have Seen this morning that the depending mdns package was updated to 2.2.10 by stating a RasPi problem.

**Comment by nzhome** [comment]
I have installed mine quite some days ago, and it already says it is 2.2.10, are you sure it was updated this morning?

"name": "mdns",
  "version": "2.2.10",
  "description": "multicast DNS service discovery",

**Comment by volschin** [comment]
Gemnasium sends me weekly mails regarding updated packages and they told me this morning it was updated in the last week.

**Comment by nzhome** [comment]
LIVE DEMO gremlins. TEST FAILED>   my iPhone today could not see the homebridge, even though the server was running like normal, and my iphone was on the one and only wifi in my house as normal..  reset my touchhome.... still no accessories...   embarassing for homebridge demo.

**Comment by nzhome** [comment]
what is going on here?  all other multicast and unicast apps on my network are currently running except for homebridge..  see, its still running here.  yet nothing in myTouchHome except for greyed out accessories.

EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] Client connection closed +44ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP connection was closed +1ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP server was closed +0ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] New connection from client +9m
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP server listening on port 54826 +1ms
EventedHTTPServer [::ffff:10.1.1.14] New connection from client +1ms
EventedHTTPServer [::ffff:10.1.1.14] HTTP server listening on port 54827 +1ms
EventedHTTPServer [::ffff:10.1.1.14] Client connection closed +0ms
EventedHTTPServer [::ffff:10.1.1.14] HTTP connection was closed +1ms
EventedHTTPServer [::ffff:10.1.1.14] HTTP server was closed +1ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP request: /pair-verify +2ms
HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP Repsonse is finished +10ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] Client connection closed +23ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP connection was closed +1ms
EventedHTTPServer [fe80::1c6e:9398:f4d6:5c32] HTTP server was closed +1ms

**Comment by nzhome** [comment]
Testing:

1) reset phone.. no go
2) reset all apps.. no go
3) reset wifi.. no go
4) reset homebridge... no go   (yes 10.1.1.14 is my iphone, so it definitely talked to each other...)

 EventedHTTPServer Server listening on port 51826 +0ms
 EventedHTTPServer [::ffff:10.1.1.14] New connection from client +2s
 EventedHTTPServer [::ffff:10.1.1.14] HTTP server listening on port 54826 +2ms
 EventedHTTPServer [::ffff:10.1.1.14] HTTP request: /pair-verify +17ms
 HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
 HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +4ms
 EventedHTTPServer [::ffff:10.1.1.14] HTTP Repsonse is finished +19ms
 EventedHTTPServer [::ffff:10.1.1.14] Client connection closed +35ms
 EventedHTTPServer [::ffff:10.1.1.14] HTTP connection was closed +2ms
 EventedHTTPServer [::ffff:10.1.1.14] HTTP server was closed +0ms

**Comment by desvdp** [comment]
@nzhome  As you'll read in the posts above I'm facing a similar issue... 

Actions taken: 
- I replaced my semi-smart-filtering switch with a dummy switch
- I removed all platforms except HUE (which I figured should be stable given the amount of people using it... in contradiction to the platform I'm developing for which I can't give any guarantees ... yet) 

Observation: since I made those changes it didn't become unavailable (but it's only like 1.5 days 'til now), I'm keeping my fingers crossed. -- I am having trouble syncing the setup between my iOS devices, but I guess that's an other issue, to be investigated later (and I don't believe this has anything to do with homebridge) --.

I suggest you have a look at you network setup just like I did and isolate components as much as possible, maybe we can find the culprit... 

What I needed to do to get stuff going again: 
There is a feature in HomeKit that prevents an accessory to be paired twice, so once it's picked up by an app you won't see it in discovery ever again. I believe there's two ways to get around this: I assume "deleting" the accessory form the app might work, but given the experimental nature it's probably better to:
- stop homebridge,
- remove the persist directory (you will loose your setup !)
- reset the homekit iOS configuration from settings/privacy/homekit (you will loose ... ! )
- restart homebridge
- discover again ...

**Comment by nzhome** [comment]
I know how to reset it.   the point is, how did it get in such a random state?  I didn't even change anything.

**Comment by nzhome** [comment]
I want to try and get it going again with out resetting homekit, nor deleting the persist folder.. I want to learn where the bug is.

**Comment by snowdd1** [comment]
I have an idea regarding this issue. I watched a comparable bahaviour when I implemented my thermostat service for the KNX device. What I saw was:
  - Seemingly randomly disconnection
  - Seemingly randomly inability to re-pair
What I found out was that in the returned /accessory URL the value did not match the minimum/maximum values. My device returned a target temperature of 0°C if none was set, HK accepts temperatures from 10°C to 38°C. And overriding the min/max values did not really work.
See https://github.com/nfarina/homebridge/issues/95#issuecomment-140319612

So if your devices return values that do not match the min/max definitions, your bridge might become blacklisted and not accessible through any homekit app, because they seem to sync this info via iCloud. I am still investigating this, as others seem to have problems with min/max values as well. As a short term solution I wrapped the `setValue` into a comparision with the min/max values for float types:

https://github.com/nfarina/homebridge/blob/master/accessories/knxdevice.js#L204
````javascript
				if (hk_value>=characteristic.minimumValue && hk_value<=characteristic.maximumValue) {
					characteristic.setValue(hk_value, undefined, 'fromKNXBus'); // 1 decoimal for HomeKit
				} else {
					this.log("Value %s out of bounds %s...%s ",hk_value, characteristic.minimumValue, characteristic.maximumValue);
				}
````
and since then it was much more reliable.
Could you give it a try?

**Comment by snowdd1** [comment]
> Could you give it a try?

And this might also apply to all the characteristics with limited allowed return values!

**Comment by desvdp** [comment]
A quick update: about 4 days ago I made a couple of changes to my setup (see my previous post in this thread). Since then, homebridge has not stopped working a single time. I meanwhile upgraded to iOS9 without a glitch... bottom line: whatever the issue is/was, I don't believe it had to do with the core homebridge/HAP-node.js

Next I'll be fetching upgrades/fixes that were made in the mean time ... and step by step include all my components again... hoping to see which causes the failure. 

My current (so far perfectly working) setup: RPi2 cabled to a 3com simple Gbit switch, an AirPort express, connected to the same switch,  is used to create a WLan (configured in "bridge" mode )...

**Comment by adekka** [comment]
I'm experiencing the same issue. The funny thing is, I added a second user/iphone. I use the app MyTouchHome. The icons became grey on my iPhone and a few minutes later it became grey on the second iPhone.

**Comment by rhearob** [comment]
I am having the same problem - after about 30 or 40 minutes, homebridge will stop running on my RPi.  The only indication is that when this happens Siri will stop responding - a bunch of I can't do that, etc.  and in my app all of the appliances will go grey or be unable t get current status.  

I am running Homebridge side by side on an Rpi with Z-Way Server using a clean installation of Raspbian Jessie, node v4.2.1.  My connection is using an edimax dongle connected via 802.11 to an Apple Airport extreme.  

Z-way is a bit flakey and I seem to notice that if Homebridge can't connect to z-way for some reason it crashes.  

What I see in the error log is this:

module.js:339
    throw err;
    ^

Error: Cannot find module '/home/pi/homebridge/app.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

I was thinking of adding a cron job that would routinely check to see if Homebridge was running and if not, start it.  Thoughts?

**Comment by julien30** [comment]
Hi,
I have the same problem.
I have a RPI with homebridge + jeedom and this plugin https://github.com/jeedom/plugin-homebridge

it's work 5-10 minutes and after icons became grey...

thank's for your help.

**Comment by julien30** [comment]
Hi,
My problem is solved after apt-get update ...

**Comment by vcrosato** [comment]
Same problem. OSX connected to ethernet then a router doing wifi bridge. Solutions? debugging tips?

**Comment by vcrosato** [comment]
While turning on my mac mini wifi might work, this will be a very ugly workaround.

**Comment by AddoSolutions** [comment]
Experiencing the same issue here.

Had it working for about a day, then after it everything appeared offline, then when I tried to remove and then re-add the homebridge it could no longer be seen.

After restarting my phone and server (Raspberry Pi 2) I was still unable to get it working.

Does it have anything to do with this?

```
Mar 11 20:31:56 raspbx homebridge[232]: at Object.LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
Mar 11 20:31:56 raspbx homebridge[232]: at Object.LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
Mar 11 20:31:56 raspbx homebridge[232]: at Server._updateCachedAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:455:20)
Mar 11 20:31:56 raspbx homebridge[232]: at process.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/cli.js:34:14)
Mar 11 20:31:56 raspbx homebridge[232]: at emitNone (events.js:68:13)
Mar 11 20:31:56 raspbx homebridge[232]: at process.emit (events.js:167:7)
Mar 11 20:31:56 raspbx homebridge[232]: at Signal.wrap.onsignal (node.js:816:46)
```

**Comment by AddoSolutions** [comment]
This **got me rolling again**:

in your `.homebridge` folder, simply remove your `persist` and `accessories` folders and re-add in your iPhone.

Ghetto, but works.  Any idea on the origin of the bug?

**Comment by apressly** [comment]
looks like this issue popped up again, now using macOS sierra and iOS 10.. not sure how to resolve

**Comment by kevingelion** [comment]
still having this issue on my raspberry pi and ios 10.

**Comment by adrianmihalko** [comment]
Same problem. It works for a day, then no response.

Home app/iOS 10/iPhone 7 + Siri
Eve app/iOS 9/iPhone 5S + Siri

Last lines of the log:

```
Thu, 10 Nov 2016 15:39:59 GMT EventedHTTPServer [::ffff:192.168.1.5] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Thu, 10 Nov 2016 15:42:49 GMT EventedHTTPServer [::ffff:192.168.1.5] Client connection closed
Thu, 10 Nov 2016 15:42:49 GMT EventedHTTPServer [::ffff:192.168.1.5] HTTP connection was closed
Thu, 10 Nov 2016 15:42:49 GMT EventedHTTPServer [::ffff:192.168.1.5] HTTP server was closed
Thu, 10 Nov 2016 15:45:32 GMT EventedHTTPServer [::ffff:192.168.1.18] Client connection error: read ETIMEDOUT
Thu, 10 Nov 2016 15:45:32 GMT EventedHTTPServer [::ffff:192.168.1.18] Client connection closed
Thu, 10 Nov 2016 15:45:32 GMT EventedHTTPServer [::ffff:192.168.1.18] HTTP connection was closed
Thu, 10 Nov 2016 15:45:32 GMT EventedHTTPServer [::ffff:192.168.1.18] HTTP server was closed
```

```
[11/10/2016, 4:04:43 PM] [eDomoticz] TV sent command succesfully.
[11/10/2016, 4:04:54 PM] [eDomoticz] Heating sent command succesfully.
[11/10/2016, 4:05:43 PM] [eDomoticz] LED sent command succesfully.
[11/10/2016, 4:05:51 PM] [eDomoticz] LED sent command succesfully.
[11/10/2016, 4:05:51 PM] [eDomoticz] LED sent command succesfully.
```

new requests are not added to the log.

**Comment by conradhagemans** [comment]
I have a similair problem. I am running Homebridge on Ubuntu 14.04. After a couple of days it stops running. 
I am running Homebridge as a service under init.d.
For now I have scheduled a cronjob to restart the service daily. 
I think the error occurs if Homebridge tries to connect to the Nest server. If it fails it stops running.

**Comment by caseywebdev** [comment]
I'm also having this issue. No errors from the homebridge logs running on an rpi. Everything will work great for anywhere from one day to a couple weeks, then every accessory reports "not responding". The only solution I've found so far is wiping the persist folder and going through the set up again.

I tried hitting `/accessories` on the rpi which returned what looks like an error code?

```
$ curl localhost:51826/accessories
{"status":-70401}
```

Googling this number didn't help much.

**Comment by msltx** [comment]
I had the same issue with iPhone (iOS10.2) showing Homebridge not responding after switching to a new Netgear ProSafe plus switch. It'll show up fine after rebooting the iPhone but will go off-line again a few minutes later. Everything was working fine before I change to the new switch.

After reading @desvdp's comment about moving back to a non-smart switch, I decided to turn off my switch's IGMP snooping and see if that may be the cause. Lo and behold, Homebridge and all my accessories show up active immediately. I'll let it run a few more days to see if Homebridge stay connected...

**Comment by caseywebdev** [comment]
Still happening for me every week or two, I just confirmed I have (and have had) IGMP snooping disabled.

**Comment by eliransapir** [comment]
@nfarina  This exact issue unfortunately happening to me once every 24 hours, igmp snooping is on as it is needed with my setup.

**Comment by msltx** [comment]
It's been over a month since I switched off IGMP snooping. Homebridge has been solid without any issues.

**Comment by gyula72** [comment]
I think  it's clearly a network issue.
I have a base router and a sub network attached for the upstairs.
Homebridge stops working on the sub network, but connecting to the basic network I can see that its still operating. Somehow its unaccessible by ios when the network accessed through a swich or a router.

Trying many setup options I ened up enabling WDS in the sub-network (bridging the base network's SSID) and voilá, it works.
