### ISSUE TITLE
iPhone with Springboard crashs after trying to pair

### ISSUE THREAD

**Issue by Kolbi** [nfarina/homebridge#192]
Hi guys,

I'm not sure if it's an Apple issue or if homebridge, so I just let you know about it:
http://forums.macrumors.com/threads/iphone-stuck-at-apple-logo-corrupt-setting.1919018/

(My iOS 9.0 iPad paired without any problems).

**Comment by KhaosT** [comment]
That looks really bad... Any chance you can get the log from the device during the boot loop (using Xcode) before another reboot happened?

**Comment by Kolbi** [comment]
Yeah, I'm not very lucky about that.

I'll try to get a log tonight. (First have to google, how to do that :))

**Comment by KhaosT** [comment]
@Kolbi You can try download Apple Configurator (https://itunes.apple.com/us/app/apple-configurator/id434433123?mt=12) and see if you can get log from device...

Given "So I connected it to my Macbook and for my surprise I could make an actual backup of my phone. So I created the backup, fully restored my phone tried iOS 9.1 PB1 and iOS 9.0 and restored the backup", this isn't a boot-loop, it's more like Springboard keep crashing so if you can get the log, I'll see what I can do there ^^

**Comment by Kolbi** [comment]
Thank you in advance!!

**Comment by Kolbi** [comment]
You should have got some mails :)

Thank you!

**Comment by KhaosT** [comment]
I'd suggest you to keep the device on and perform a reset HomeKit from another device (that signed into same iCloud account) which may help Notification Center on current device to recover... If that doesn't work, I guess you'll either have to reset the whole device, manually edit the backup file (remove files about notification center history) and then restore that backup.

**Comment by Kolbi** [comment]
Hi, thank you for your advice.

I can test it later this week (the iPhone is on the way to Apple to be replaced).

Restoring the backup need a lot of time... but I'm first trying to restore it. Delete HomeKit from another device (my current iPhone 4S) and if that doesn't help I have to make a new backup from the restored backup but this time unencrypted. At the point manually editing backup file I might need your help again :)

I hope my backup is not damaged already, I have run https://deciphertools.com/decipher-backup-repair.html and it showed me some file size errors within my backup...

**Comment by Kolbi** [comment]
My phone is back, I'm now trying to restore the backup. I connected my iPhone 4S with homebridge. 

After restoring I'm going to delete all HomeKit data from the 4S and after that I try to delete the app via iTunes from my iPhone 6. 

I hope it reboots then...


Could you see froms Log which App produces the issue in Springboard?

**Comment by KhaosT** [comment]
Based on the crash report you sent, Notification Center itself crashes…

**Comment by Kolbi** [comment]
Yesterday I tried to restore the backup on my iPhone 6 with 9.0.1 and after an hour or so it's stil stuck at the last point (step 6) on synching ("Auf das Anwenden der Änderungen warten" / "Waiting for apply the changes"). By the way copying the apps also needs a lot of time like everything (I guess because the Springboard reboots).

Tonight I'm going to try to restore the backup on iOS 9.1 Public Beta 2 (maybe the springboard issue is fixed in PB2?).

My problem is that my backup is encrypted and I guess I'm not able to modify it - or do you know a method? Creating an unencrypted backup is not possible because it can't fully restore the encrypted.

**Comment by KhaosT** [comment]
@Kolbi yeah, it's not possible to modify an encrypted backup and also not possible to create an unencrypted backup without first restoring the encrypted backup to iOS device... It's really strange that misbehaved notification can cause issue like this. If iOS 9.1b2 doesn't fix the issue, I guess you'll have to setup iPhone without restoring backup...

**Comment by KhaosT** [comment]
@Kolbi btw, if you have TimeMachine enabled on your computer, you may be able to recover by restoring an older backup.

**Comment by Kolbi** [comment]
@KhaosT yeah I might have an backup from August (?) available but I'm not sure if I'm going to restore it to my iPhone 6.

Sadly I'm doing to less backups (Time Machine and iOS) to have an actual backup in the backhand. Yeah I know I'm always telling to friends to do regularly backups as an IT expert I might should do it as well :) but as a fact that I'm using an external usb disk for TimeMachine backups I'm to lazy to do it regularly. Local Time Machine backups has been disabled because of to less space on my SSD. But I'm going to have a look at it tonight. Maybe "El Captain" has enabled it again.

Maybe I'm going to restore the old Backup to my iPhone 4S and going to build up everything from scratch on my iPhone 6 with the 4S as template.

But my last hope is that PB2 is able to boot with the latest backup. That would be great.

**Comment by AppleTechy** [comment]
Since there have been multiple ios and homebridge updates and no more activity on this issue, I will assume your issue has long been resolved.
