### ISSUE TITLE
Can't run two platforms together - config.json issue?

### ISSUE THREAD

**Issue by danwalton84** [nfarina/homebridge#474]
I have installed Homebridge, along with plugins for Nest thermostat and Harmony Hub.

I can control either of them perfectly well with Siri when using a config.json file specifically for either the Nest platform or the Harmony Hub platform, but can't seem to create a config.json file which will allow me to control both at the same time. At the moment, I have been swapping the config.json files in the .homebridge folder to achieve this.

I guess what I want it something like this (below - xx's replace sensitive info etc), but I can't make it work together. How can I run two platforms together?

-----

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "987-65-432"
	},

	"platforms": [{
		"platform": "Nest",
		"username": "dxxxx@xxxxx.com",
		"password": "xxxxxxxxx",
        
		"platform": "HarmonyHub",
		"name": "Lounge",
		"ip_address": "xx.xxx.xx.xx"
	}]
}

**Comment by AppleTechy** [comment]
This issue is that your platform block should look like this
 "platforms": [
{
    "platform": "Nest",
    "username": "dxxxx@xxxxx.com",
    "password": "xxxxxxxxx",
}
{
    "platform": "HarmonyHub",
    "name": "Lounge",
    "ip_address": "xx.xxx.xx.xx"
}
]

**Comment by KhaosT** [comment]
The "platforms" is expecting an array of platforms. In your example, you created an array with only 1 platform …

**Comment by KhaosT** [comment]
@AppleTechy you missed the comma between two😏

**Comment by danwalton84** [comment]
Thanks! So where should the missing comma be?

**Comment by AppleTechy** [comment]
@KhaosT whoops  I just copied and pasted their example and forgot to add the common after adding the brackets in the correct spot. Guess I can't be trusted to fix every thing

**Comment by AppleTechy** [comment]
@danwalton84 I fixed by example above in my original comment

**Comment by danwalton84** [comment]
Great, I'll give this a go now.

**Comment by AppleTechy** [comment]
@danwalton84 Let me know if that works

**Comment by danwalton84** [comment]
I'm really sorry to come back to this, but I can't get it to validate.

I've replaced the platform block, but it gives me parse errors on a few different lines when I try to validate it.

This is the best I can get - but i'm still getting an error I can't work out on the last line:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "987-65-432"
	},

	"platforms": [{
		"platform": "Nest",
		"username": "dxxxx@xxxxx.com",
		"password": "xxxxxxxxx"
	}, {
		"platform": "HarmonyHub",
		"name": "Lounge",
		"ip_address": "xx.xxx.xx.xx"
	}]

**Comment by AppleTechy** [comment]
Oops another mistake... {
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "987-65-432"
},

"platforms": [
{
    "platform": "Nest",
    "username": "dxxxx@xxxxx.com",
    "password": "xxxxxxxxx"
}, 
{
    "platform": "HarmonyHub",
    "name": "Lounge",
    "ip_address": "xx.xxx.xx.xx"
}
]
}

**Comment by AppleTechy** [comment]
@danwalton84 ^

**Comment by AppleTechy** [comment]
@danwalton84 Did that fix the son validation error?

**Comment by danwalton84** [comment]
Worked like a charm, thanks a lot - much appreciated :+1:

**Comment by AppleTechy** [comment]
No problem, glad I could help!

**Comment by RickHOZ** [comment]
Hi Appletechy, 

I have been having the same issue that @danwalton84 has been having an I have followed your instructions above on numerous occasions but I simply can't seem to get it to work.

I would really appreciate any help you can give as this is driving me mad. I can get both Platforms to work independently but when I try and combine and then check the code it is not good. ( I have also tried loading it in homebridge and it does not work )

See screenshot below and under that the full config file.

![screen shot 2017-10-30 at 9 18 03 pm](https://user-images.githubusercontent.com/33169283/32168383-2ac9d914-bdb8-11e7-8183-fd0edd251b88.png)
 

Complete config.json file:

{
  "bridge": {
    "name": "Samara",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "My home HomeKit API configuration file",

  "platforms": [
    {
      "platform": "ElkM1",
      "name": "ElkM1",
      "elkAddress": "192.168.1.2",
      "elkPort": "2101",
      "area": "1",
      "keypadCode": "xxxx",
      "zoneTypes": {
      "1": "contact",
      "2": "contact",
      "3": "contact",
      "4": "contact",
      "5": "motion",
      "6": "motion",
      "7": "motion",
      "8": "motion",
      "openOutput":"11",
      "closeOutput":"11",
      "name":"Garage door"
    },
  {
      "platform": "homebridge-cbus.CBus",
      "name": "CBus",
      "client_ip_address": "127.0.0.1",
      "client_controlport": 20023,
      "client_cbusname": "SAMARA",
      "client_network": 254,
      "client_application": 56,
      "client_debug": true,

      "platform_export": "/Users/SamaraServer/.homebridge/samara_platform.json",
    },
    ]
  }

      "accessories": [
        { "type": "light", "id": 11, "name": "Office lights" },
        { "type": "light", "id": 12, "name": "Office Store"},
        { "type": "light", "id": 74, "name": "AirCon Office"},
        { "type": "light", "id": 13, "name": "Office Toilet"},
        { "type": "dimmer", "id": 18, "name": "Office Hall"},
        { "type": "light", "id": 50, "name": "Office Toilet Exhaust Fan"},


        { "type": "dimmer", "id": 1, "name": "Master Bedroom"},
        { "type": "light", "id": 75, "name": "Master Suite AirCon"},
        { "type": "shutter", "id": 63, "name": "Master Suite Shear", "invert": "false"},
        { "type": "shutter", "id": 64, "name": "Master Suite Curtain", "invert": "false"},
        { "type": "light", "id": 2, "name": "Master Suite Feature"},
        { "type": "dimmer", "id": 3, "name": "Master Suite Ensuite"},
        { "type": "light", "id": 4, "name": "Master Suite Ensuite Mirror"},
        { "type": "dimmer", "id": 5, "name": "Master Suite Toilet"},
        { "type": "light", "id": 6, "name": "Master Suite Robe"},
        { "type": "light", "id": 48, "name": "Master Suite Ensuite Exhaust Fan"},
        { "type": "light", "id": 49, "name": "Master Suite Toilet Exhaust Fan"},
        { "type": "light", "id": 83, "name": "Master Suite Windows Close"},
        { "type": "light", "id": 144, "name": "Master Suite Windows Open)"},


        { "type": "dimmer", "id": 7, "name": "Retreat"},
        { "type": "dimmer", "id": 8, "name": "Retreat Cove"},
        { "type": "dimmer", "id": 9, "name": "Retreat Stairs"},
        { "type": "light", "id": 76, "name": "AirCon Retreat"},
        { "type": "light", "id": 145, "name": "Retreat Feature"},



        { "type": "dimmer", "id": 15, "name": "Media Room"},
        { "type": "dimmer", "id": 16, "name": "Media Cove"},
        { "type": "light", "id": 73, "name": "AirCon Media"},


        { "type": "dimmer", "id": 21, "name": "Kitchen"},
        { "type": "light", "id": 22, "name": "Kitchen Benches"},
        { "type": "light", "id": 71, "name": "AirCon Kitchen"},
        { "type": "light", "id": 86, "name": "Kitchen Bulkhead"},


        { "type": "light", "id": 23, "name": "Scullery"},


        { "type": "dimmer", "id": 24, "name": "Dining Room"},
        { "type": "light", "id": 10, "name": "House Features"},


        { "type": "dimmer", "id": 26, "name": "Lounge"},
        { "type": "light", "id": 72, "name": "AirCon Lounge"},
        { "type": "light", "id": 85, "name": "Fireplace"},

        { "type": "dimmer", "id": 40, "name": "Sala Treatment Room"},
        { "type": "dimmer", "id": 38, "name": "Sala"},
        { "type": "light", "id": 39, "name": "Sala Feature"},
        { "type": "light", "id": 56, "name": "Sala Bathroom Exhaust Fan"},


        { "type": "light", "id": 35, "name": "Laundry"},
        { "type": "light", "id": 36, "name": "Laundry Store"},
        { "type": "light", "id": 37, "name": "Laundry Clothesline"},
        { "type": "dimmer", "id": 19, "name": "Laundry Hall"},
        { "type": "light", "id": 110, "name": "Externals Rear and Clothesline"},


        { "type": "light", "id": 45, "name": "Pool Pump Room"},
        { "type": "light", "id": 46, "name": "Wine Cellar"},


        { "type": "light", "id": 67, "name": "Fountain"},
        { "type": "light", "id": 68, "name": "Garden Lighting"},
        { "type": "light", "id": 69, "name": "Green Garden Lights"},
        { "type": "light", "id": 58, "name": "Pond Light"},
        { "type": "light", "id": 57, "name": "Pond Pump"},


        { "type": "light", "id": 70, "name": "Pool Lights"},
        { "type": "light", "id": 62, "name": "Pool Spa Blower"},
        { "type": "light", "id": 43, "name": "Deck Pool"},
        { "type": "light", "id": 60, "name": "Pool Pump"},
        { "type": "light", "id": 61, "name": "Pool Spa Pump"},



        { "type": "dimmer", "id": 28, "name": "Bridge Suite"},
        { "type": "dimmer", "id": 29, "name": "Bridge Suite Ensuite"},
        { "type": "light", "id": 30, "name": "Bridge Suite Ensuite Mirror"},
        { "type": "light", "id": 77, "name": "Bridge Suite AirCon"},
        { "type": "light", "id": 44, "name": "Bridge Suite Deck"},
        { "type": "light", "id": 53, "name": "Bridge Suite Ensuite Exhaust Fan"},
        { "type": "light", "id": 66, "name": "Bridge Suite AV Features"},


        { "type": "dimmer", "id": 31, "name": "Kingfisher Bed"},
        { "type": "light", "id": 78, "name": "Kingfisher Bed AirCon"},

        { "type": "dimmer", "id": 32, "name": "Kingfisher lounge"},
        { "type": "light", "id": 79, "name": "Kingfisher Lounge AirCon"},

        { "type": "dimmer", "id": 33, "name": "Bathroom Kingfisher"},
        { "type": "light", "id": 54, "name": "Bathroom Exhaust Fan Kingfisher"},
        { "type": "dimmer", "id": 34, "name": "Kingfisher Toilet"},
        { "type": "light", "id": 55, "name": "Kingfisher Toilet Exhaust Fan"},

        { "type": "dimmer", "id": 20, "name": "Guest Hall"},


        { "type": "light", "id": 47, "name": "Portico"},
        { "type": "switch", "id": 80, "name": "Front Door Open", "activeDuration": "5s"},
        { "type": "light", "id": 87, "name": "Chandelier"},
        { "type": "light", "id": 25, "name": "Foyer"},

        { "type": "switch", "id": 105, "name": "Front Gate Open", "activeDuration": "100ms"},
        { "type": "switch", "id": 103, "name": "Garage Door Open", "activeDuration": "100ms"},
        { "type": "light", "id": 14, "name": "Garage"},

        { "type": "light", "id": 52, "name": "Solar Hot Water Boost"},

        { "type": "dimmer", "id": 112, "name": "Lounge Feature 1"},
        { "type": "dimmer", "id": 113, "name": "Lounge Feature 2"}
      ]
    }
  ],
  "accessories": [ ]
}

**Comment by magnusaurus** [comment]
I am also having the same issue as rickHOZ. Can't validate my json and trying to add multiple platforms. My config is simple really, don't know what I am missing? 
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
        },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
        ],

    "platforms": [
        {
            "platform": "netatmo",
            "name": "netatmo weather",
            "ttl": 5,
            "auth": {
            "client_id": "xxxxxxx",
            "client_secret": "xxxxxxxx",
            "username": "magnxxxxx",
            "password": "xxxxx"

        },
        {
            "platform": "Arlo",
            "name": "Arlo",
            "email": "magnus.berg@xxxxxx.se",
            "password": "xxxxxx",
            "stay_arm": "mode2",
            "night_arm":"mode3"
        }
        ]
        }
`

**Comment by owtritebrawla** [comment]
I am having a problem can anyone tell me what i am doing wrong im getting an error message Thank you
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
			"platform": "TplinkSmarthome",
			"name": "TplinkSmarthome"
		},
		{
			"platform": "tcc",
			"name": "Thermostat",
			"username": ".....",
			"password": ".....",
			"devices": "deviceID": "1234567",
			"name": "Other Floor"
		}
	]
}

**Comment by NorthernMan54** [comment]
For the tcc plugin you need [] brackets around devices and name.  Look at the tcc readme sample closely

**Comment by owtritebrawla** [comment]
> > {
> > "bridge": {
> > "name": "Homebridge",
> > "username": "CC:22:3D:E3:CE:30",
> > "port": 51826,
> > "pin": "031-45-154"
> > },
> > 
> > "platforms": [{
> > "platform": "TplinkSmarthome",
> > "name": "TplinkSmarthome"
> > },
> > {
> > "platform": "tcc",
> > "name": "Thermostat",
> > "username": ".....",
> > "password": ".....",
> > ["devices": "deviceID": "1234567",]
> > ["name": "Other Floor"]
> > }
> > ]
> > }

When I added the[] brackets I am still getting an error.

**Comment by owtritebrawla** [comment]
<img width="1088" alt="screen shot 2018-02-23 at 12 27 42 pm" src="https://user-images.githubusercontent.com/36755438/36607600-f6ba61fe-18be-11e8-81da-b84324bf5fe7.png">
please see image

**Comment by owtritebrawla** [comment]
I got it to work. Is Siri able to turn heat over to AC or all you can do is change the temperature?

**Comment by NorthernMan54** [comment]
I have never tried

**Comment by Matthoff1930** [comment]
Sorry a bit new to this stuff... Been struggling for few hours... I have my config.json set up for nest thermostat working perfectly. But I'm trying to add 2 lift master garage doors to the home bridge and having no luck at all... I got it to display my IDs for each door but I still get an error when following the guide about Having an existing uuid. Any assistance would be great!
