### ISSUE TITLE
homebridge opens random ports

### ISSUE THREAD

**Issue by taconugget** [nfarina/homebridge#816]
Homebridge is launching successfully but is starting up on random ports. It completely disregards whats in config.jason:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "00:1E:06:33:5A:36",
        "port": 51826,
        "pin": "011-45-156"
    },
```

On one launch it will launch it will look like this:
`[9/28/2016, 7:39:29 PM] Homebridge is running on port 37833.`
and on the next like this:
`[9/28/2016, 7:39:54 PM] Homebridge is running on port 57192.`

Running on UbuntuMate64 // Odroid C2 // Node v4.5.0 // Homebridge 0.4.2

Here is what happens on boot:

```
homebridge -D
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/28/2016, 7:43:36 PM] Loaded plugin: homebridge-wink
[9/28/2016, 7:43:36 PM] Registering platform 'homebridge-wink.Wink'
[9/28/2016, 7:43:36 PM] ---
[9/28/2016, 7:43:36 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/28/2016, 7:43:36 PM] ---
[9/28/2016, 7:43:36 PM] Loading 1 platforms...
[9/28/2016, 7:43:36 PM] [Wink] Initializing Wink platform...
[9/28/2016, 7:43:36 PM] [Wink] Fetching Wink devices.
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Hub
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 86176, Name Dinning Table
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 86178, Name Living Room
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID undefined, Name Camera
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 94596, Name Atrium
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 98964, Name Front Door
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 101100, Name Kitchen
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 101117, Name Formal Living Room
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 104063, Name Bathroom
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 104767, Name Couch Lamp
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 104802, Name Patio
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 104813, Name Hallway
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Hallway
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Formal Living Room
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Kitchen
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Living Room
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Bedroom Remote
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group binary_switches, ID 8914, Name Back Yard
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 105755, Name Front Yard
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored By Group - Group thermostats, ID 49444, Name Home Home Thermostat
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group smoke_detectors, ID 41057, Name Home Living Room Nest Protect
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group smoke_detectors, ID 41058, Name Home Hallway Nest Protect
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID undefined, Name Camera
[9/28/2016, 7:43:38 PM] [Wink] Device Added - Group light_bulbs, ID 1659865, Name Kids Hall
[9/28/2016, 7:43:38 PM] [Wink] Device Ignored Not In HomeKit - Group hubs, ID 32151, Name Kids remote
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Dinning Table'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Living Room'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Atrium'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Front Door'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Kitchen'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Formal Living Room'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Bathroom'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Couch Lamp'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Patio'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Hallway'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Back Yard'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Front Yard'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Home Living Room Nest Protect'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Home Hallway Nest Protect'...
[9/28/2016, 7:43:38 PM] [Wink] Initializing platform accessory 'Kids Hall'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 011-45-156 │
    └────────────┘

[9/28/2016, 7:43:38 PM] Homebridge is running on port 34917.
```

**Comment by KhaosT** [comment]
@taconugget in order to add IP camera support to underlying framework HAP-NodeJS, I removed the ability to set the port which server should be running. Is there a particular reason why you need homebridge to run on a fixed port?

**Comment by taconugget** [comment]
@KhaosT machine is fire-walled with UFW. If it doest launch with a fixed port number how do I allow the packets to pass without opening the firewall? If there is a workaround Im happy to try it.

Thanks

**Comment by KhaosT** [comment]
@taconugget that make sense. I addressed the problem with homebridge 0.4.5

**Comment by taconugget** [comment]
@KhaosT Thank you sir

**Comment by klein0r** [comment]
Has this issue been solved? Have the same problem in my docker environment - I have no idea which port I have to forward to the host since the homebridge port is random.

**Comment by jlemonier** [comment]
I am hoping to rely on Homebridge extensively for my home.  I am still seeing the "random port" issue.  I do not see a branch or version of 0.4.5.  Can that be pulled in to master?
